name: Security

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack install

      - run: pnpm audit --audit-level critical
